-- Phase 0.5 -- Governance pillar: Government Authorities and Sector
-- Stakeholders.
--
-- Source: elev8-country-admin-config_3.html's Governance section. Both
-- tables are normalized (not nested in pillar_configs' governance
-- payload) because the mockup's own note says so explicitly:
-- "Authorities registered here can be granted approval rights in
-- Procurement, Investment, Sustainability and ICV workflows" -- these
-- are cross-pillar reference data, same reasoning as country_ftas and
-- country_hs_codes, not governance-specific settings. Escalation Matrix
-- and Data Governance & Access Policy (the other 2 of Governance's 4
-- sections) stay in pillar_configs.payload where pillar='governance',
-- since those genuinely are governance-only settings -- see
-- docs/modules/config-engine/README.md.
--
-- ref is a short human-readable reference code, generated by the
-- application layer at insert time (count of existing rows + 1, not a
-- Postgres sequence) -- not perfectly race-safe under concurrent inserts
-- from the same country, acceptable for this admin tool's actual usage
-- pattern (one Country Admin, occasional adds), flagged here rather than
-- silently assumed fine forever.
--
-- Rollback:
--   drop table if exists public.country_stakeholders;
--   drop table if exists public.country_authorities;

create table public.country_authorities (
  id uuid primary key default gen_random_uuid(),
  country_id uuid not null references public.countries(id) on delete cascade,
  ref text not null,
  name text not null,
  type text not null,
  domain text not null,
  headquarters text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (country_id, ref),

  constraint country_authorities_type_check check (
    type in (
      'Procurement Authority', 'Investment Authority', 'Trade Authority',
      'Customs Authority', 'Sustainability Authority', 'Standards Authority'
    )
  ),
  constraint country_authorities_domain_check check (
    domain in ('Procurement', 'Investment', 'Sustainability', 'Both')
  )
);

create index on public.country_authorities (country_id);

alter table public.country_authorities enable row level security;

create policy "country_authorities_select_any_authenticated"
  on public.country_authorities for select
  to authenticated
  using (true);

create policy "country_authorities_write_country_admin_only"
  on public.country_authorities for all
  to authenticated
  using (is_country_admin(country_id))
  with check (is_country_admin(country_id));

create table public.country_stakeholders (
  id uuid primary key default gen_random_uuid(),
  country_id uuid not null references public.countries(id) on delete cascade,
  ref text not null,
  name text not null,
  sectors text[] not null default '{}',
  domain text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (country_id, ref),

  constraint country_stakeholders_domain_check check (
    domain in ('Procurement', 'Investment', 'Sustainability', 'Both')
  )
);

create index on public.country_stakeholders (country_id);

alter table public.country_stakeholders enable row level security;

create policy "country_stakeholders_select_any_authenticated"
  on public.country_stakeholders for select
  to authenticated
  using (true);

create policy "country_stakeholders_write_country_admin_only"
  on public.country_stakeholders for all
  to authenticated
  using (is_country_admin(country_id))
  with check (is_country_admin(country_id));
